**5.16 List 2 Dimensi**


In [1]:
#percoban dalam list 2 dimensi
matrik = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
print(matrik)
#percobaan penarikan nilai matrik

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [2]:
matrik[1]
#percobaan penarikan nilai matrik pada baris pertama

[5, 6, 7, 8]

In [3]:
matrik[1][2]

7

In [4]:
for baris in matrik:
  print(baris)
  for kolom in baris:
      print(kolom)

[1, 2, 3, 4]
1
2
3
4
[5, 6, 7, 8]
5
6
7
8
[9, 10, 11, 12]
9
10
11
12
[13, 14, 15, 16]
13
14
15
16


**5.17 *Tuples***


In [5]:
#percobaan dengan metode tuples
angka = (0,1,1,3,4,5)
#percobaan mencetak data yang dimulai dari data ke nol 
print(angka[0])
#mencetak data yg dimulai dari nol sampai ketiga
print(angka[0:3])
#mencetak isi dalam data angka dari yang ke nol sampai ketiga
for isi in angka[0:3]:
  print(isi)


0
(0, 1, 1)
0
1
1


In [7]:
angka[0] = 10
#percobaan tersebut eror  karna metode tuples tidak dapat diganti

TypeError: ignored

######**5.18 *Dictionaries***

In [8]:
Data_orang = {
    "nama" : "ketut gacoan",
    "umur" : 17,
    "apakah singel" : False
}
#percobaan metode Dictionaries agar dapat mencetak suatu data orang 

In [9]:
print(Data_orang['nama'])

ketut gacoan


######**5.19 Fungsi dalam python**

In [10]:
def full_nama(first_name,last_name):
  print(f"nama lengkapnya adalah {first_name} {last_name}")
  #percobaan metode fungsi dalam python


In [11]:
first_name = input("nama depannya adalah"+" ")
last_name = input("nama belakangnya adalah"+" ")
nickname = input("biasa dipanggil"+" ")
full_nama(first_name,last_name)
#percobaan metode fungsi dalam python, dengan mencetak nama lengkap atau full name
#disini saya mencoba menginput first name, last name, untyk mencetak ful name, dan nick name untuk mencetak nama panggilan


nama depannya adalah I Komang
nama belakangnya adalah Triatmaja Putra
biasa dipanggil Devano
nama lengkapnya adalah I Komang Triatmaja Putra


**5.20 *numpy***

In [2]:
import numpy as np 
#memanggil library numpy

**5.20.1** **Perintah Dasar pada Numpy**

In [3]:
a = np.array([7,22,24,26])
print("data a yaitu: ")
print(a)
print('\n')
#numpy akan menjadikan array sebagai matriks 
#data dalam '[ ]' akan menjadi baris 

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("data b yaitu: ")
print(b)
print('\n')
#numpy akan menjadikan array sebagai matriks 
#data dalam '[[ ]]' akan menjadi kolom

c = np.array([[[1,2,3], [3,4,5]],
             [[6,7,8], [9,10,11]],
             [[12,13,14], [15,16,17]]])
print("data c yaitu: ")
print(c)
print('\n')
#numpy akan menjadikan array sebagai matriks 
#data dalam '[[[ ]]]' akan menjadi kolom dan setiap '[[ ]]' akan berisi spasi

print("banyak kolom pada data c dan")
c.ndim
#ndim adalah untuk menampilkan banyaknya baris dalam suatu data 
print("banyak baris pada data b adalah")
b.shape
#shape adalah untuk menampilkan banyaknya kolom dalam suatu data 
#jika kita memanggil dengan cara ini maka hasil yang keluar akan menjadi satu 
#karena out dalam satu comment hanya bisa satu out
#jadi hasil yang akan ditampilkan adalah (3,3)
#kolom pada data c adalah 3 dan baris pada data b adalah 3

data a yaitu: 
[ 7 22 24 26]


data b yaitu: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


data c yaitu: 
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


banyak kolom pada data c dan
banyak baris pada data b adalah


(3, 3)

**5.20.2 memanggil Anggota, Kolom, dan Baris dengan Numpy**

In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print('\n')
#data tersebut diatas  akan terlihat pada hasil menjadi  suatu kolom 

#b[baris data, kolom data]
#semuanya dihitung mulai dari 0 
b[0,2]
#berarti memanggil baris pertama kolom ke tiga 
#dan pada data terbetuk angka yang menempati baris pertama kolom ke tiga yakni angka 3 

[[1 2 3]
 [4 5 6]
 [7 8 9]]




3

In [5]:
b[0,0] = 99
#ini akan mengubah data b baris pertama kolom pertama dari angka 1 menjadi 99
print(b)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [6]:
b[1,:]
#memanggil semua baris kedua

array([4, 5, 6])

**5.20.3 matrix pada numpy**

In [7]:
np.zeros((3,2))
#ones berarti membuat semua entri pada matriks tersebut menjadi angka 0
#membuat matriks ordo 3x2 dengan entri 0

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.full((3,2),8)
#membentuk array dengan satu bentuk entri pada seluruh data 
#pada percobaan ini menggunakan angka 8

array([[8, 8],
       [8, 8],
       [8, 8]])

**5.20.4 Copy pada Numpy**

In [9]:
a = np.array([7,22,24,26])
print("data a")
print(a)
print('\n')

b = a.copy()
print("coppy")
print(b)
print('\n')
#copy data menggunakan fungsi copy
#a merupakan data aslinya dan b adalah copy-an 

b[0] = 10
print("diubah")
print(b)
print('\n')
#ubah data b yang merupakan copy-an 
#angka pertama diubah menjadi angka 10
#jadi data b hasilnya akan [10 22 24 26]

print("data a")
print(a)
#data a akan tetap sama seperti awal tidak berubah sama sekali 
#karena yang diubah adalah copyan nya yaitu data b

data a
[ 7 22 24 26]


coppy
[ 7 22 24 26]


diubah
[10 22 24 26]


data a
[ 7 22 24 26]


**5.20.5 Operasi Matematika pada Numpy**

In [10]:
a= np.array([1,2,3,4])
print(a)
b = np.array([5,10,15,20])
print(b)
#masukkan dulu data yang  di operasikan 

[1 2 3 4]
[ 5 10 15 20]


In [13]:
#tanda + merupakan suatu  operasi penjumlahan
a+b


array([ 6, 12, 18, 24])

In [14]:
#tanda - adalah operasi pengurangan 
b-b

array([0, 0, 0, 0])

In [15]:
#tanda ** adalah operasi pangkat 
a**5

array([   1,   32,  243, 1024])

In [16]:
#tanda / adalah operasi pembagian 
b/a

array([5., 5., 5., 5.])

**5.20.6 Perkalian Matrik pada Numpy**

In [17]:
import numpy as np
p = np.array([[1,2,3,4],[5,6,7,8]])
print("matriks p")
print(p)
print('\n')

q = np.array([[7,22,24,26],[2,4,6,8]])
print("matriks q")
print(q)
print('\n')

r = p*q
print("perkalian masing masing entri p dan q")
print (r)
print('\n')
#tanda * akan mengalikan masing masing entri
#r= data p dikali data q 

s = ([[1,2],[3,4],[5,6],[7,8]])
t = np.matmul(p,s)
print("perkalian matriks p dan s")
print(t)
#matmul berfungsi untuk mengalikan dua matriks 
#pada t di minta matriks pxs 

matriks p
[[1 2 3 4]
 [5 6 7 8]]


matriks q
[[ 7 22 24 26]
 [ 2  4  6  8]]


perkalian masing masing entri p dan q
[[  7  44  72 104]
 [ 10  24  42  64]]


perkalian matriks p dan s
[[ 50  60]
 [114 140]]


**5.20.7 min, max dan sum pada Numpy**

In [19]:
import numpy as np
c = np.array([[8,7,6], 
              [5,4,3],
              [2,1,1] ])
print("array data c")
print(c)
print('\n')

#"min" digunakan untuk mencari data minimum 
h = np.min(c)
print("nilai minimum")
print(h)
print('\n')

#"min axis=0" digunakan untuk mencari data minimum pada baris data 
#axis=0 menunjukan baris
z = np.min(c, axis=0)
print("nilai minimum baris")
print(z)
print('\n')

#"min axis=1" digunakan untuk mencari data minimum pada kolom data 
#axis=1 menunjukan kolom
f = np.min(c, axis=1)
print("nilai minimum kolom")
print(f)
print('\n')

#"max" digunakan untuk mencari data maksimum
g = np.max(c)
print("nilai maksimum")
print(g)
print('\n')
#"max axis=0" digunakan untuk mencari data maksimum pada baris data 
#axis=0 menunjukan baris
i = np.max(c, axis=0)
print("nilai maksimum baris")
print(i)
print('\n')

#"max axis=1" digunakan untuk mencari data maksimum pada kolom data 
#axis=1 menunjukan kolom
j = np.max(c, axis=1)
print("nilai maksimum kolom")
print(j)
print('\n')

#"sum" digunakan untuk menghitung jumlah seluruh data
k = np.sum(c)
print("jumlah seluruh data")
print(k)
print('\n')

#"sum axis=0" digunakan untuk menghitung jumlah data pada baris 
#axis=0 menunjukan baris
l = np.sum(c, axis=0)
print("jumlah data baris")
print(l)
print('\n')

#"sum axis=1" digunakan untuk menghitung jumlah data pada kolom  
#axis=1 menunjukan kolom
m = np.sum(c, axis=1)
print("jumlah data kolom")
print(m)

array data c
[[8 7 6]
 [5 4 3]
 [2 1 1]]


nilai minimum
1


nilai minimum baris
[2 1 1]


nilai minimum kolom
[6 3 1]


nilai maksimum
8


nilai maksimum baris
[8 7 6]


nilai maksimum kolom
[8 5 2]


jumlah seluruh data
37


jumlah data baris
[15 12 10]


jumlah data kolom
[21 12  4]
